-- EXPLORE ALL OBJECTS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES


-- EXPLORE ALL COLUMNS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-- EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM
SELECT DISTINCT 
country
FROM gold.dim_customers


-- EXPLORE ALL PRODUCT CATEGORIIES "THE MAJOR DIVISIONS"
SELECT DISTINCT
category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1,2,3


-- FIND THE DATE OF THE FIRST AND THE LAST ORDER
-- HOW MANY YEARS OF SALES ARE AVAILABLE
SELECT
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS years_of_sales
FROM gold.fact_sales


-- FIND THE YOUNGEST AND THE OLDEST CUSTOMER 
SELECT
MAX(birthdate) AS youngest_customer,
MIN(birthdate) AS oldest_customer
FROM gold.dim_customers


-- FIND THE TOTAL SALES
SELECT
SUM(sales_amount) AS total_sales
FROM gold.fact_sales


-- FIND HOW MANY ITEMS ARE SOLD
SELECT
SUM(quantity) AS total_items
FROM gold.fact_sales


-- FIND THE AVERAGE SELLING PRICE
SELECT
AVG(price) AS avg_selling_price
FROM gold.fact_sales


-- FIND THE TOTAL NO. OF ORDERS
SELECT
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales


-- FIND THE TOTAL NO. OF PRODUCTS
SELECT
COUNT(DISTINCT product_key) AS total_products
FROM gold.fact_sales


-- FIND THE TOTAL NO. OF CUSTOMERS
SELECT
COUNT(customer_key) AS total_customers
FROM gold.dim_customers


-- FIND THE TOTAL NO. OF CUSTOMERS THAT HAVE PLACED AN ORDER
SELECT
COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales


-- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS

SELECT 'Total sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total items' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'avg_selling_price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total products' AS measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers


-- FIND TOTAL CUSTOMERS BY COUNTRIES
SELECT
country,
COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC


-- FIND TOTAL CUSTOMERS BY GENDER
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- FIND TOTAL PRODUCTS BY CATEGORY
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC


-- WHAT IS THE AVERAGE COSTS IN EACH CATEGORY ?
SELECT
category,
AVG(product_cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC


-- WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY ?
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES ?
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC


-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE ?
SELECT TOP 5 
p.product_name,
SUM(f.sales_amount) AS revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY revenue DESC


-- WHAT ARE THE 5 WOST-PERFORMING PRODUCTS IN TERMS OF SALES ?
SELECT TOP 5 
p.product_name,
SUM(f.sales_amount) AS revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY revenue


-- FIND THE TOP 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC


-- FIND THE TOP 3 CUSTOMERS WITH FEWEST ORDERS PLACED
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_orders
